# database container
db:
  image: postgres:9.4
  environment:
    - POSTGRES_PASSWORD=mysecretpassword
    - POSTGRES_USER=postgres
    - DB=postgres
  volumes:
    - ./pgdata:/var/lib/postgresql/data
# rabbitmq container
redis:
  image: redis
# container with Django web server
web:
  build: .  # build using default Dockerfile
  command: ./run_web.sh
  volumes:
    - .:/app  # mount current directory inside container
  # ports:
  #   - "8000:8000"
  # set up links so that web knows about db and redis
  links:
    - db:db
    - redis:redis
# nginx
nginx:
    image: nginx
    volumes: 
      - ./nginx:/etc/nginx/conf.d
    volumes_from:
      - web
    ports:
      - "80:80"
# container with rabbit worker
worker:
  build: .
  command: ./run_celery.sh
  volumes:
    - .:/app
  links:
    - db:db
    - redis:redis
